name: Test PowerShell on Windows
on:
  push: # Trigger on any push to any branch
    branches:
      - '**' # Matches all branches
  pull_request: # Trigger on pull request events
    branches:
      - '**' # Matches all branches for pull request events

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Invoke Pester Tests
        shell: pwsh
        run: |
          [System.Io.FileInfo]$PsRoot = $PSScriptRoot
          #Grabbing main folder path
          $ProjectRoot = ($PsRoot.Directory).Parent
          $TestsFolder = Join-Path -Path $ProjectRoot.FullName -ChildPath "Tests"
          write-host "Invoking tests in $TestsFolder"
          invoke-pester $TestsFolder #-OutputFile $ProjectRoot\testresults.xml -OutputFormat NUnitXml -PassThru -Show Summary
